### ISSUE TITLE
Trigger causing crash

### ISSUE THREAD

**Issue by mjm2000** [ComradDoge/DogeEU4#11]
I keep crashing some reason around 1500, this is the last error message  
[triggerimplementation.cpp:14247]: Script error! Script Object Token: "has_port", Error: Trigger condition set on the wrong scope: Scope.GetProvince()

The full error files.
[error.log](https://github.com/ComradDoge/DogeEU4/files/6512875/error.log)
[exception.txt](https://github.com/ComradDoge/DogeEU4/files/6512877/exception.txt)

Here is my save
https://www.dropbox.com/s/wq3z1s92qxip4p6/autosave.eu4?dl=0

**Comment by mjm2000** [comment]
An update in 
common/advisortypes/AE_advisortypes.txt  common/advisortypes/IDV_advisors.txt

I commented out has_colonist and has_port but I'm now i'm getting the error but for the vassal condition

**Comment by ComradDoge** [comment]
Seems to be going fine on my branch so I am going to assume I fixed
